apiVersion: v1
kind: Pod
metadata:
  name: repo-clone-pod
spec:
  containers:
    - name: repo-cloner
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e
          REPO_NAME=$(basename -s .git "$REPO_URL")
          STORAGE_PATH="/mnt/data/repo/$ORG_ID/$REPO_NAME"
          
          # Create parent directory if it doesn't exist
          mkdir -p "/mnt/data/repo/$ORG_ID"
          
          # Remove directory if it exists (force removal)
          if [ -d "$STORAGE_PATH" ]; then
            rm -rf "$STORAGE_PATH"
          fi
          
          # Clone the repository
          echo "Cloning repository to $STORAGE_PATH..."
          git clone "$REPO_URL" "$STORAGE_PATH"
          
          # Keep container running for debugging
          echo "Clone completed successfully. Keeping container alive..."
          sleep 3600
      env:
        - name: REPO_URL
          value: "https://github.com/trufflesecurity/test_keys.git"
        - name: ORG_ID
          value: "1611"
      volumeMounts:
        - mountPath: /mnt/data/repo
          name: repo-storage
  volumes:
    - name: repo-storage
      persistentVolumeClaim:
        claimName: repo-pvc
  restartPolicy: Never