apiVersion: v1
kind: Pod
metadata:
  name: trufflehog-pod
  labels:
    app: trufflehog
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    # fsGroup: 1000
  containers:
    - name: trufflehog
      image: python:3.12-slim  # Use Python image
      command: ["/bin/sh", "-c"]
      args:
        - |
          apt-get update && apt-get install -y git curl tar dnsutils 
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          git config --global --add safe.directory /data/repo
          while true; do sleep 30; done
      volumeMounts:
        - name: repo-storage
          mountPath: /mnt/data/repo
      env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017"
  volumes:
    - name: repo-storage
      persistentVolumeClaim:
        claimName: repo-pvc
