apiVersion: v1
kind: Pod
metadata:
  name: trufflehog-pod
  labels:
    app: trufflehog
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    # fsGroup: 1000
  containers:
    - name: trufflehog
      image: trufflesecurity/trufflehog:latest
      command: ["/bin/sh", "-c"]
      args:
        - trufflehog filesystem /mnt/data/repo/$ORG_ID/$REPO_NAME --only-verified --no-update --json > /mnt/data/repo/$ORG_ID/results/$REPO_NAME/trufflehog_result.json;
      volumeMounts:
        - name: repo-storage
          mountPath: /mnt/data/repo
      env:
        - name: REPO_NAME
          value: "test_keys"  # You can update this dynamically later
        - name: ORG_ID
          value: "1611"  # You can update this dynamically later
  volumes:
    - name: repo-storage
      persistentVolumeClaim:
        claimName: repo-pvc
  restartPolicy: Never
