apiVersion: v1
kind: Pod
metadata:
  name: gitleaks-pod
  labels:
    app: gitleaks
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    # fsGroup: 1000
  containers:
    - name: gitleaks
      image: python:3.12-slim  # Use Python image
      command: ["/bin/sh", "-c"]
      args:
        - |
          apt-get update && apt-get install -y git wget tar dnsutils 
          pip install pymongo
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.21.1/gitleaks_8.21.1_linux_x64.tar.gz
          tar -xvzf gitleaks_8.21.1_linux_x64.tar.gz
          rm gitleaks_8.21.1_linux_x64.tar.gz
          mv gitleaks /usr/bin/gitleaks
          git config --global --add safe.directory /data/repo
          while true; do sleep 30; done
      volumeMounts:
        - name: repo-volume
          mountPath: /data/repo
      env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017"
  volumes:
    - name: repo-volume
      emptyDir: {}  # or persistentVolumeClaim if you want persistent storage
  restartPolicy: OnFailure
