apiVersion: v1
kind: Pod
metadata:
  name: gitleaks-pod
  labels:
    app: gitleaks
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    # fsGroup: 1000
  containers:
    - name: gitleaks
      image: zricethezav/gitleaks:latest
      command: ["/bin/sh", "-c"]
      args:
        - gitleaks detect --source=/mnt/data/repo/$ORG_ID/$REPO_NAME --report-format=json --report-path=/mnt/data/repo/$ORG_ID/results/$REPO_NAME/gitleaks_result.json --exit-code=0;
      volumeMounts:
        - name: repo-storage
          mountPath: /mnt/data/repo
      env:
        - name: REPO_NAME
          value: "test_keys"  # You can update this dynamically later
        - name: ORG_ID
          value: "1611"  # You can update this dynamically later

  volumes:
    - name: repo-storage
      persistentVolumeClaim:
        claimName: repo-pvc
  restartPolicy: Never
